Clarify one-way binding behaviour for objects
canjs/can-stache-bindings pull request #183
Opened 2017-04-20 23:42 UTC by christopherjbaker

Part of me wants to expand the notes a bit more, but the docs seem very terse. Is it worth including an example of this behaviour? And is there a workaround?

fixes #128

2017-04-21 00:41 UTC, chasenlehara commented
I think it would be helpful to have a new section about the difference between one-way binding values and objects, and link to that section from each of those notes.

2017-04-24 14:44 UTC, matthewp commented
![giphy](https://cloud.githubusercontent.com/assets/361671/25342768/00a1655c-28db-11e7-9e42-90e8a8832cdd.gif)

2017-04-25 16:24 UTC, chasenlehara approved these changes
Thanks for adding the additional docs!

2017-04-26 20:48 UTC, justinbmeyer requested changes
Thanks for taking a stab at this!  When you have a sec, lets brainstorm about how to best incorporate my feedback.

2017-04-26 20:48 UTC, justinbmeyer commented on docs/bindings.md
> +@group can-stache-bindings.notes Notes
We probably shouldn't have a notes group.  Nothing else is like that and it would be unexpected.

2017-04-26 20:48 UTC, justinbmeyer commented on docs/one-way-objects.md
> +Generally, this binding only observes changes in one direction, but when [can-stache.key] is an object (POJO, DefineMap, etc), changes to the object itself are two-way; the one-way only applies to th
this sentence is hard for me to follow.  

> this binding

Which binding?  One way binding for object, one-way to child, or one-way to parent?

> changes to the object itself are two-way

what does this mean?  Does this mean that the object can be changed?

2017-04-26 20:48 UTC, justinbmeyer commented on docs/one-way-objects.md
> +## One Way Binding for Objects
this should probably be a section under `can-stache-bindings`

2017-04-26 20:48 UTC, justinbmeyer commented on docs/one-way-objects.md
> +// parent-component
are components needed to demonstrate this?

2017-04-26 20:48 UTC, justinbmeyer commented on docs/one-way-objects.md
> +    obj: 'object',
afaik, `object` isn't a valid `type` setting.  Did you mean `any`?

2017-04-26 23:56 UTC, christopherjbaker commented
Reworked the docs to show a plain javascript example, rather than explain. Cannot merge as the links are not working yet (figuring that out), but I wanted to push so the text could be reviewed.

2017-05-14 01:37 UTC, justinbmeyer requested changes

2017-05-14 01:37 UTC, justinbmeyer commented on docs/bindings.md
> +> __Note:__ If the value is an object, changes to its properties will still be updated. See <a href="#OneWayBindingWithObjects">One Way Binding With Objects</a>.
If value being passed to the component is an object, changes to the objects properties will still be visible to the component.  Objects are passed by reference.   See <a href="#OneWayBindingWithObjects">One Way Binding With Objects</a>.

2017-05-14 01:37 UTC, justinbmeyer commented on docs/bindings.md
> +> __Note:__ If the value is an object, changes to its properties will still be updated. See <a href="#OneWayBindingWithObjects">One Way Binding With Objects</a>.
Make a similar change as the one above.

2017-07-10 21:31 UTC, justinbmeyer approved these changes

2017-07-11 00:38 UTC, merged