add warnings for non-existing values (fixes #136)
canjs/can-stache-bindings pull request #191
Opened 2017-04-27 15:53 UTC by christopherjbaker

This may break tests in other repos if they have warning checks. (as my previous add-warnings PR did).

2017-05-14 01:46 UTC, justinbmeyer requested changes
I think for https://github.com/canjs/can-stache-bindings/issues/119, this needs to just see there's no view model on the element and warn if someone's binding to one that isn't there.  I also think we should only warn if we've got a scope->child and `scope` is undefined.

2017-05-14 01:46 UTC, justinbmeyer commented on can-stache-bindings.js
> +			if (typeof childCompute() === "undefined") {
childCompute() === undefined

2017-05-22 21:57 UTC, christopherjbaker commented
I'm not sure what to check for. Might need to pair on this to figure it out.

2017-07-10 14:51 UTC, justinbmeyer submitted a review, later dismissed
I think this should look for `domData.get(el,"viewModel")`.

2017-08-07 17:01 UTC, phillipskevin approved these changes

2017-08-07 17:01 UTC, merged