#214 - add docs for space-separated scope event syntax
canjs/can-stache-bindings pull request #215
Opened 2017-05-30 19:04 UTC by mickmcgrath13

resolves #214

2017-05-30 19:11 UTC, justinbmeyer requested changes

2017-05-30 19:11 UTC, justinbmeyer commented on docs/event.md
> +@param {can-stache/expressions/key-lookup} SCOPE_KEY_LOOKUP A key to specify what scope the SCOPE_EVENT is in.
not really the "scope"  ... there's only one scope.  It's really what object's (or event emitters) events should be bound to.

2017-05-30 19:11 UTC, justinbmeyer commented on docs/event.md
> +<my-component (. someevent)="doSomething()"/>
can we use something other than `.`?  Maybe show a bit more of an example to make the context more clear?

2017-05-30 19:11 UTC, justinbmeyer commented on docs/event.md
> +@signature `(SCOPE_KEY_LOOKUP SCOPE_EVENT)='CALL_EXPRESSION'`
Maybe this should just be `KEY_LOOKUP` and `EVENT`

2017-05-30 19:11 UTC, justinbmeyer commented on docs/event.md
> +@param {String} SCOPE_EVENT An event in the specified scope.
The name of the event on an event emitter specified by `KEY_LOOKUP`.

2017-05-30 19:14 UTC, mickmcgrath13 commented on docs/event.md
> +@signature `(SCOPE_KEY_LOOKUP SCOPE_EVENT)='CALL_EXPRESSION'`
👍

2017-05-30 19:14 UTC, mickmcgrath13 commented on docs/event.md
> +<my-component (. someevent)="doSomething()"/>
👍

2017-05-30 19:25 UTC, mickmcgrath13 commented on docs/event.md
> +@param {can-stache/expressions/key-lookup} SCOPE_KEY_LOOKUP A key to specify what scope the SCOPE_EVENT is in.
Would 'context' be better, or is that something different, too?

"A key to specify the context for the SCOPE_EVENT."

2017-05-31 16:42 UTC, justinbmeyer requested changes

2017-05-31 16:42 UTC, justinbmeyer commented on docs/event.md
> +var scope = new DefineMap({
var context

2017-05-31 16:42 UTC, justinbmeyer commented on docs/event.md
> +In this example, `activityrecorder` exists on the current scope and is defined as:
is on the current context

2017-05-31 16:42 UTC, justinbmeyer commented on docs/event.md
> +@param {can-stache/expressions/key-lookup} KEY_LOOKUP A key to specify the context for the `EVENT`.
A key to specify the context for the `EVENT` binding. The object specified by `key` will have its event named `EVENT` bound.

2017-08-15 13:57 UTC, justinbmeyer commented
If we've never added docs for this, we probably shouldn't.  Instead we should make sure the new binding syntax `on:something:by:somethingElse` is documented and works.

2017-08-22 18:52 UTC, phillipskevin commented
`on:foo:by:obj` is documented and works. Docs will be released in 3.10.0.

2017-08-22 18:52 UTC, closed without merging