Fixing the QUnit.ok usage
canjs/can-stache-bindings pull request #219
Opened 2017-06-06 14:49 UTC by obaidott

Fixes incorrect usage of QUnit.ok as mentioned in canjs/canjs#3276

Closes #211

2017-06-06 16:08 UTC, phillipskevin requested changes

2017-06-06 16:08 UTC, phillipskevin commented on test/bindings-test.js
> +			ok(called, "1", "update called once");
This should also be using `equal`.

2017-06-06 16:08 UTC, phillipskevin commented on test/bindings-test.js
> +// test('scope method called when nested scope property changes (#216)', function(){
why did this get commented out?

2017-06-27 14:52 UTC, andrejewski commented
I stole this and put it in #242; thank @obaidott

2017-06-27 14:52 UTC, closed without merging